### ISSUE TITLE
Runtime error on first run on new map

### ISSUE THREAD

**Issue by h4ml3t** [minetest-mods/craftguide#104]
I'm getting this error whenever I create a new world and load it for the first time:

> ERROR[Main]: ModError: Runtime error from mod 'craftguide' in callback on_mods_loaded(): .../craftguide/init.lua:1450: standard output file is closed  
ERROR[Main]: stack traceback:  
ERROR[Main]: 	[C]: in function 'write'  
ERROR[Main]: 	.../craftguide/init.lua:1450: in function 'iop'  
ERROR[Main]: 	.../craftguide/init.lua:1467: in function '?'  
ERROR[Main]: 	.../minetest/bin/../builtin/game/register.lua:429: in function <.../minetest/bin/../builtin/game/register.lua:413>

Note:  
This started to happen after that I've installed Sofar's Crops mod; without it no error happens.

**Comment by kilbith** [comment]
Fixed: https://github.com/minetest-mods/craftguide/commit/3f34d275c1822405943c8861b30653fc0fb14ef8

**Comment by h4ml3t** [comment]
It's still happening.  
Note that the error does not happen on the second time you load a map.

That is:
First run -> Error.
Second run -> No error.

**Comment by kilbith** [comment]
Fixed (the easy way): https://github.com/minetest-mods/craftguide/commit/689840d6f5a530befa4755161a4d5e4c743ea340

**Comment by h4ml3t** [comment]
> Fixed (the easy way): [689840d](https://github.com/minetest-mods/craftguide/commit/689840d6f5a530befa4755161a4d5e4c743ea340)

Thank you for your work :)
